export const imageLinks = [
  { id: 1, url: "src/assets/images/photo1.png" },
  { id: 2, url: "src/assets/images/photo2.png" },
  { id: 3, url: "src/assets/images/photo3.png" },
  { id: 4, url: "src/assets/images/photo4.png" },
  { id: 5, url: "src/assets/images/photo5.png" },
  { id: 6, url: "src/assets/images/form1.png" },
  { id: 7, url: "src/assets/images/form2.png" },
  { id: 8, url: "src/assets/images/form3.png" },
  { id: 9, url: "src/assets/images/form4.png" },
  { id: 10, url: "src/assets/images/form5.png" },
  { id: 11, url: "src/assets/images/form6.png" },
  { id: 12, url: "src/assets/images/form7.png" },
  { id: 13, url: "src/assets/images/form8.png" },
  { id: 14, url: "src/assets/images/form9.png" },
  { id: 15, url: "src/assets/images/form10.png" },
  { id: 16, url: "src/assets/images/form11.png" },
  { id: 17, url: "src/assets/images/form12.png" },
  { id: 18, url: "src/assets/images/form13.png" },
  { id: 19, url: "src/assets/images/form14.png" },
  { id: 20, url: "src/assets/images/form15.png" },
  { id: 21, url: "src/assets/images/form16.png" },
  { id: 22, url: "src/assets/images/form17.png" },
  { id: 23, url: "src/assets/images/form18.png" },
  { id: 24, url: "src/assets/images/form19.png" },
  { id: 25, url: "src/assets/images/form20.png" },
  { id: 26, url: "src/assets/images/form21.png" },
  { id: 27, url: "src/assets/images/form22.png" },
];

export const mobileBreakpoint = 540;
